2020-05-23 21:48:00.275 [error] <0.538.0> Failed to start Ranch listener 'Elixir.Chats.Endpoint.HTTP' in ranch_tcp:listen([{cacerts,'...'},{key,'...'},{cert,'...'},{ip,{0,0,0,0}},{port,4000}]) for reason eaddrinuse (address already in use)
2020-05-23 22:41:32.309 [error] <0.590.0> CRASH REPORT Process <0.590.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 3,clauses => nil,function => split,kind => nil,module => 'Elixir.String'},[{'Elixir.String',split,[nil,<<" ">>,[]],[{file,"lib/string.ex"},{line,471}]},{'Elixir.Chats.Router','-do_match/4-fun-5-',2,[{file,"lib/chat_api/router.ex"},{line,57}]},{'Elixir.Chats.Router',dispatch,2,[{file,"lib/plug/router.ex"},{line,259}]},{'Elixir.Chats.Router',plug_builder_call,2,[{file,"lib/chat_api/router.ex"},{line,...}]},...]},...} in 'Elixir.Plug.Cowboy.Handler':exit_on_error/4 line 68 in 'Elixir.Plug.Cowboy.Handler':exit_on_error/4 line 68
2020-05-23 22:41:32.368 [error] <0.590.0> Cowboy stream 1 with ranch listener 'Elixir.Chats.Endpoint.HTTP' and connection process <0.589.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 3,clauses => nil,function => split,kind => nil,module => 'Elixir.String'},[{'Elixir.String',split,[nil,<<" ">>,[]],[{file,"lib/string.ex"},{line,471}]},{'Elixir.Chats.Router','-do_match/4-fun-5-',2,[{file,"lib/chat_api/router.ex"},{line,57}]},{'Elixir.Chats.Router',dispatch,2,[{file,"lib/plug/router.ex"},{line,259}]},{'Elixir.Chats.Router',plug_builder_call,2,[{file,"lib/chat_api/router.ex"},{line,...}]},...]},...} in 'Elixir.Plug.Cowboy.Handler':exit_on_error/4 line 68
2020-05-23 22:44:48.665 [error] <0.656.0> CRASH REPORT Process <0.656.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 3,clauses => nil,function => split,kind => nil,module => 'Elixir.String'},[{'Elixir.String',split,[nil,<<" ">>,[]],[{file,"lib/string.ex"},{line,471}]},{'Elixir.Chats.Router','-do_match/4-fun-5-',2,[{file,"lib/chat_api/router.ex"},{line,57}]},{'Elixir.Chats.Router',dispatch,2,[{file,"lib/plug/router.ex"},{line,259}]},{'Elixir.Chats.Router',plug_builder_call,2,[{file,"lib/chat_api/router.ex"},{line,...}]},...]},...} in 'Elixir.Plug.Cowboy.Handler':exit_on_error/4 line 68 in 'Elixir.Plug.Cowboy.Handler':exit_on_error/4 line 68
2020-05-23 22:44:48.697 [error] <0.656.0> Cowboy stream 1 with ranch listener 'Elixir.Chats.Endpoint.HTTP' and connection process <0.655.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 3,clauses => nil,function => split,kind => nil,module => 'Elixir.String'},[{'Elixir.String',split,[nil,<<" ">>,[]],[{file,"lib/string.ex"},{line,471}]},{'Elixir.Chats.Router','-do_match/4-fun-5-',2,[{file,"lib/chat_api/router.ex"},{line,57}]},{'Elixir.Chats.Router',dispatch,2,[{file,"lib/plug/router.ex"},{line,259}]},{'Elixir.Chats.Router',plug_builder_call,2,[{file,"lib/chat_api/router.ex"},{line,...}]},...]},...} in 'Elixir.Plug.Cowboy.Handler':exit_on_error/4 line 68
2020-05-23 22:49:42.370 [error] <0.660.0> CRASH REPORT Process <0.660.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 2,function => post,message => nil,module => 'Elixir.HTTPotion',reason => nil},[{'Elixir.HTTPotion',post,[<<"localhost:4000/match/get-match">>,[{body,<<"{\"liked_profile_id\":null,\"current_profile_id\":1}">>},{headers,[{<<"Content-type">>,<<"application/json">>},{<<"authorization">>,<<"dsghkajdsafisdfsd,maioansuge">>}]}]],[]},{'Elixir.Chats.Router','-do_match/4-fun-5-',2,[{file,"lib/chat_api/router.ex"},{line,...}]},...]},...} in 'Elixir.Plug.Cowboy.Handler':exit_on_error/4 line 68 in 'Elixir.Plug.Cowboy.Handler':exit_on_error/4 line 68
2020-05-23 22:49:42.372 [error] <0.660.0> Cowboy stream 1 with ranch listener 'Elixir.Chats.Endpoint.HTTP' and connection process <0.659.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 2,function => post,message => nil,module => 'Elixir.HTTPotion',reason => nil},[{'Elixir.HTTPotion',post,[<<"localhost:4000/match/get-match">>,[{body,<<"{\"liked_profile_id\":null,\"current_profile_id\":1}">>},{headers,[{<<"Content-type">>,<<"application/json">>},{<<"authorization">>,<<"dsghkajdsafisdfsd,maioansuge">>}]}]],[]},{'Elixir.Chats.Router','-do_match/4-fun-5-',2,[{file,"lib/chat_api/router.ex"},{line,...}]},...]},...} in 'Elixir.Plug.Cowboy.Handler':exit_on_error/4 line 68
2020-05-23 22:52:50.468 [error] <0.791.0> CRASH REPORT Process <0.791.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Poison.SyntaxError',message => <<"Unexpected end of input at position 0">>,pos => nil,token => nil},[{'Elixir.Poison.Parser','parse!',2,[{file,"lib/poison/parser.ex"},{line,55}]},{'Elixir.Poison','decode!',2,[{file,"lib/poison.ex"},{line,83}]},{'Elixir.Chats.Router','-do_match/4-fun-5-',2,[{file,"lib/chat_api/router.ex"},{line,74}]},{'Elixir.Chats.Router',dispatch,2,[{file,"lib/plug/router.ex"},{line,259}]},{'Elixir.Chats.Router',plug_builder_call,...},...]},...} in 'Elixir.Plug.Cowboy.Handler':exit_on_error/4 line 68 in 'Elixir.Plug.Cowboy.Handler':exit_on_error/4 line 68
2020-05-23 22:52:50.497 [error] <0.791.0> Cowboy stream 1 with ranch listener 'Elixir.Chats.Endpoint.HTTP' and connection process <0.790.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Poison.SyntaxError',message => <<"Unexpected end of input at position 0">>,pos => nil,token => nil},[{'Elixir.Poison.Parser','parse!',2,[{file,"lib/poison/parser.ex"},{line,55}]},{'Elixir.Poison','decode!',2,[{file,"lib/poison.ex"},{line,83}]},{'Elixir.Chats.Router','-do_match/4-fun-5-',2,[{file,"lib/chat_api/router.ex"},{line,74}]},{'Elixir.Chats.Router',dispatch,2,[{file,"lib/plug/router.ex"},{line,259}]},{'Elixir.Chats.Router',plug_builder_call,...},...]},...} in 'Elixir.Plug.Cowboy.Handler':exit_on_error/4 line 68
2020-05-23 22:57:45.879 [error] <0.573.0> CRASH REPORT Process <0.573.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Mariaex.Error',action => nil,connection_id => <0.568.0>,mariadb => #{code => 1216,message => <<"Cannot add or update a child row: a foreign key constraint fails">>},message => nil,reason => nil,tag => nil},[{'Elixir.Ecto.Adapters.MySQL',insert,6,[{file,"lib/ecto/adapters/mysql.ex"},{line,209}]},{'Elixir.Ecto.Repo.Schema',apply,4,[{file,"lib/ecto/repo/schema.ex"},{line,547}]},{'Elixir.Ecto.Repo.Schema','-do_insert/4-fun-1-',14,[{file,"lib/..."},...]},...]},...} in 'Elixir.Plug.Cowboy.Handler':exit_on_error/4 line 68 in 'Elixir.Plug.Cowboy.Handler':exit_on_error/4 line 68
2020-05-23 22:57:45.895 [error] <0.573.0> Cowboy stream 1 with ranch listener 'Elixir.Chats.Endpoint.HTTP' and connection process <0.572.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Mariaex.Error',action => nil,connection_id => <0.568.0>,mariadb => #{code => 1216,message => <<"Cannot add or update a child row: a foreign key constraint fails">>},message => nil,reason => nil,tag => nil},[{'Elixir.Ecto.Adapters.MySQL',insert,6,[{file,"lib/ecto/adapters/mysql.ex"},{line,209}]},{'Elixir.Ecto.Repo.Schema',apply,4,[{file,"lib/ecto/repo/schema.ex"},{line,547}]},{'Elixir.Ecto.Repo.Schema','-do_insert/4-fun-1-',14,[{file,"lib/..."},...]},...]},...} in 'Elixir.Plug.Cowboy.Handler':exit_on_error/4 line 68
2020-05-23 23:01:29.755 [error] <0.668.0> CRASH REPORT Process <0.668.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => open,kind => nil,module => 'Elixir.AMQP.Connection'},[{'Elixir.AMQP.Connection',open,[nil],[{file,"lib/amqp/connection.ex"},{line,19}]},{'Elixir.Chats.Router','-do_match/4-fun-5-',2,[{file,"lib/chat_api/router.ex"},{line,82}]},{'Elixir.Chats.Router',dispatch,2,[{file,"lib/plug/router.ex"},{line,259}]},{'Elixir.Chats.Router',plug_builder_call,2,[{file,"lib/chat_api/rout..."},...]},...]},...} in 'Elixir.Plug.Cowboy.Handler':exit_on_error/4 line 68 in 'Elixir.Plug.Cowboy.Handler':exit_on_error/4 line 68
2020-05-23 23:01:29.782 [error] <0.668.0> Cowboy stream 1 with ranch listener 'Elixir.Chats.Endpoint.HTTP' and connection process <0.667.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => open,kind => nil,module => 'Elixir.AMQP.Connection'},[{'Elixir.AMQP.Connection',open,[nil],[{file,"lib/amqp/connection.ex"},{line,19}]},{'Elixir.Chats.Router','-do_match/4-fun-5-',2,[{file,"lib/chat_api/router.ex"},{line,82}]},{'Elixir.Chats.Router',dispatch,2,[{file,"lib/plug/router.ex"},{line,259}]},{'Elixir.Chats.Router',plug_builder_call,2,[{file,"lib/chat_api/rout..."},...]},...]},...} in 'Elixir.Plug.Cowboy.Handler':exit_on_error/4 line 68
